version: '3.7'

services:
  app:
    container_name: orpen-service
    build:
      context: .
    command: npm run start:prod
    ports:
      - 3007:3007
    networks:
      - backend

networks:
  backend:
    driver: bridge
